### ISSUE TITLE
Multiple proposal keys for regular users

### ISSUE THREAD

**Issue by uhbif19** [flow-hydraulics/flow-wallet-api#195]
As far as I understand, a regular user cannot do his transactions concurrently.

Only admin can use multiple proposal keys. Is it possible to port this ability to an ordinary user?

**Comment by nanuuki** [comment]
hi @uhbif19! you're correct. This is certainly a feature that can be added. Do you have any specifics regarding your use case?

The most straightforward way to do this would be to add an endpoint for adding keys to a specific account, for example for an existing account with 1 key:

```
POST /v1/accounts/{address}/add-keys HTTP/1.1
content-type: application/json

{
  "keyCount": 4
}
```

☝️ this would duplicate the main key for the account so that there would be a total of 1+4 = 5 copies of it (with key indexes 0-4).

Another option would be to specify the number of keys in the config and adding the keys at creation time for each new account.

I am assuming that the main purpose of this feature would be to allow concurrent transactions and as such the keys can be cloned instead of creating new private keys.

**Comment by uhbif19** [comment]
Thank you for the answer.

I did not know about `add-keys`, will try it.

> Another option would be to specify the number of keys in the config and adding the keys at creation time for each new account.

I did not understand about option. Is that option is already usable?

> Do you have any specifics regarding your use case?
> I am assuming that the main purpose of this feature would be to allow concurrent transactions and

Yes, I want to do multiple transactions from the same account

**Comment by sheerryy** [comment]
@nanuuki can we get any ETA for this feature?

**Comment by nanuuki** [comment]
@sheerryy I'm working on an initial implementation for this feature, it should be done pretty soon but latest next week :) The initial version will enable multiple keys for all custodial accounts, with a configurable number of keys (same for all custodial accounts that are created through the API).

**Comment by nanuuki** [comment]
@sheerryy @uhbif19 As #235 was merged it's now possible to configure new accounts to have more than one key. Hopefully this is useful to you :)

FYI: We're working on a feature to manually "sync" existing accounts to have the configured number of keys, no ETA on that yet though.
