### ISSUE TITLE
Production readiness?

### ISSUE THREAD

**Issue by gta14** [flow-hydraulics/flow-wallet-api#311]
Hi, thanks for your support of this project! In the README it states not to use this for production. Can anyone offer some advice on what parts of this service are not considered to be production-ready? Just trying to gauge the level of effort required to fully productize a solution based on this service.

**Comment by nvdtf** [comment]
Hi, sorry for the late response here. 
From my perspective everything is operational in Wallet API as it is. It was flagged "not ready for production" because there was no full-time team supporting and closing issues and fix bugs.
Anybody who adopts this project needs to add any needed features themselves.
This being said, with the introduction of hybrid custody we're looking to add this repo back to our top maintenance list.
